Add support for metadata component
CycloneDX/cyclonedx-python-lib pull request #118
Opened 2022-01-04 12:17 UTC by artem-smotrakov

Part of #6

Signed-off-by: Artem Smotrakov <asmotrakov@riotgames.com>

2022-01-04 13:45 UTC, jkowalleck approved these changes

2022-01-04 13:46 UTC, madpah commented
Thanks for the PR @artem-smotrakov. We're in the process of a notable update at present to support the forthcoming CycloneDX 1.4 schema - so please forgive us if we wait for that work to stabilise before we look at merging your PR.

Cheers!

2022-01-04 13:50 UTC, jkowalleck commented
> Thanks for the PR @artem-smotrakov. We're in the process of a notable update at present to support the forthcoming CycloneDX 1.4 schema - so please forgive us if we wait for that work to stabilise before we look at merging your PR.
> 
> Cheers!


enabled CI to run CT/QA.

@artem-smotrakov could you check that all tests pass?
see https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/CONTRIBUTING.md for more.

2022-01-04 14:04 UTC, artem-smotrakov commented
Hmm, I read the contributing guidelines and ran tests and `poetry run autopep8 --in-place -r .` before opening the PR. They passed. Let me check again.

2022-01-04 15:06 UTC, artem-smotrakov commented
I've fixed several formatting and typing issues. `poetry run tox` passed. Please re-run the CI/CD jobs.

2022-01-13 10:35 UTC, madpah commented
Hi @artem-smotrakov - we've just merged changes for CycloneDX 1.4 - are you willing to rebase this branch from main?

Thanks, Paul

2022-01-13 12:29 UTC, artem-smotrakov commented
@madpah I've rebased it -- please rerun CI/CD and have a look at the updates.

I am not sure about this one:

https://github.com/CycloneDX/cyclonedx-python-lib/pull/118/files#diff-9c84a99c5332704dd6a90a4defadfd9df437336f07b79b91033e0a96bbd8fbf1R95

I've noticed that if a BOM doesn't have components, `_specialise_output_for_schema_version()` fails with a key error. I've updated it to always add `components` element. That is how XML encoder behaves.

2022-01-13 13:19 UTC, madpah requested changes
@artem-smotrakov - thanks again for the PR.

It's interesting you have pointed out that `components` is output as an empty element in some cases - ideally this should not be output if there are no Components - but we are happy to resolve this as a separate bug later.

2022-01-13 13:19 UTC, madpah commented on cyclonedx/model/bom.py
> +        Set a Component for this Bom Metadata.
@artem-smotrakov - I've tried to mirror the descriptions provided in the Specification here - so ideally this doc would read:

> The (optional) component that the BOM describes.

2022-01-13 13:19 UTC, madpah commented on cyclonedx/output/xml.py
> +        if bom_metadata.component is not None:
You don't need the `is not None` - `if bom_metadata.component` suffices

2022-01-13 13:35 UTC, artem-smotrakov commented
@madpah I've addressed your comments -- thanks for the review!

2022-01-13 13:48 UTC, madpah approved these changes

2022-01-13 14:41 UTC, merged