Added Dependency Model
CycloneDX/cyclonedx-python-lib pull request #137
Opened 2022-01-19 07:42 UTC by Kravcu

Hello everyone,

I'd like to contribute and help with adding dependencies, I'd appreciate if you could take a look at this code and say what's wrong here.

2022-01-19 08:28 UTC, madpah commented
Hi @Kravcu - thanks for the contribution. Can you open an Issue Ticket to describe the feature/fix etc. that you are contributing please? It will help us (and the community) understand and track the change.

2022-01-19 08:31 UTC, madpah commented
I think perhaps you are looking to implement #7 @Kravcu - awesome!

Will review the PR and provide any comments.

2022-01-19 08:46 UTC, madpah requested changes

2022-01-19 08:46 UTC, madpah commented on cyclonedx/model/component.py
> +        self.__dependencies = dependencies or []
I would move this to be with line 153 (suggestion).

2022-01-19 08:46 UTC, madpah commented on cyclonedx/model/component.py
> +        Get all the Dependencies for this Component.
We've been trying to utilise the descriptions for attributes as provided in the CycloneDX Specification - this doc would be:

> Defines the direct dependencies of a component. Components that do not have their own dependencies MUST be declared as empty elements within the graph. Components that are not represented in the dependency graph MAY have unknown dependencies. It is RECOMMENDED that implementations assume this to be opaque and not an indicator of a component being dependency-free.

2022-01-19 08:46 UTC, madpah commented on cyclonedx/model/dependency.py
> +class Dependency:
Missing class documentation.

2022-01-19 08:46 UTC, madpah commented on cyclonedx/model/dependency.py
> +        self.purl = purl
Can you please add @property getter/setting methods for `purl`.

2022-01-19 08:46 UTC, madpah commented on cyclonedx/output/json.py
> +        data_to_generate_json = {**self._create_bom_element(), **bom_json}
Love this change 👍

2022-01-19 08:46 UTC, madpah commented on cyclonedx/output/serializer/json.py
> +        # PackageURL
Interesting you've added this code @Kravcu - myself and the other maintainers struggled with JSON serialisation of `PackageURL` objects as they are extensions of `tuple`, which the JSON serializer handles before the `default()` method is called - so this code will never be reached.

Our workaround was lines 86-89 below.

2022-01-19 08:46 UTC, madpah commented on cyclonedx/output/serializer/json.py
> +    def serialize_component_dependencies(cls, c: Component) -> Dict[str, Union[str, List[str]]]:
The issue here is that `bom-ref`'s for Components are not guaranteed to the PURLs.

Each Component now has a `bom-ref` attribute which should be used.

2022-01-19 08:48 UTC, madpah commented
@Kravcu - I've added some review points to the PR - the main point is the assumption that Components will be referenced using a PURL, which is not the case I'm afraid.

Aside from the PR comments, there are a couple of other hygiene points to look at:
1. You need to sign your commits - please check [CONTRIBUTING](https://github.com/CycloneDX/cyclonedx-python-lib/blob/master/CONTRIBUTING.md)
2. Few static analysis violations have been reported

Thanks again and don't hesitate to ask any questions.

2022-01-20 10:18 UTC, jkowalleck commented
@madpah  @Kravcu 
we might need to discuss and document, if a set of dependencies should modify the hash of a component,
and therefore be part of `__hash__`.

2022-04-20 12:25 UTC, madpah commented
This has been implemented now through #210.

2022-04-20 12:25 UTC, closed without merging