chore(deps): update poetry and other dependency versions
CycloneDX/cyclonedx-python-lib pull request #369
Opened 2023-03-26 11:04 UTC by gruebel

Originally I juste wanted to update `packageurl` with the added type hints to remove the type ignores, I also found a typing issue in `cyclonedx/serialization/__init__.py` but I couldn't upgrade the `poertry.lock` file, so I had to use the latest 1.4.1 version and they changed the lock file version to 2.0, which looks now different. This probably also the reason, why all the dependabot PRs are failing 🤔

2023-03-28 10:24 UTC, jkowalleck commented
partially duplicates #358

2023-03-28 13:10 UTC, gruebel commented
@jkowalleck didn't see that PR 🙈 I can wait till it is merged and then recreate my with the type hint changes.

2023-03-30 07:43 UTC, madpah commented
#358 has been merged to main now @gruebel - thanks for your patience!

2023-03-30 16:12 UTC, jkowalleck requested changes
Could you rebase and incorporate my remarks?

2023-03-30 16:12 UTC, jkowalleck commented on cyclonedx/serialization/__init__.py
> +    def deserialize(cls, o: object) -> UUID:
:+1:

2023-03-30 16:12 UTC, jkowalleck commented on cyclonedx/model/bom.py
> +    from packageurl import PackageURL
therefore, we need to update 
https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/pyproject.toml#L51

and not only the lock file

2023-03-31 09:01 UTC, gruebel commented
@jkowalleck I lower bound `packageurl-python` as requested 🙂

2023-03-31 09:12 UTC, jkowalleck commented
you need to upgrade the lowest-lockfile too,
see https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/pyproject.toml#L48

2023-03-31 10:30 UTC, jkowalleck approved these changes

2023-03-31 10:34 UTC, jkowalleck commented
LGTM, @madpah

2023-03-31 11:52 UTC, madpah approved these changes

2023-03-31 11:52 UTC, merged