Main
CycloneDX/cyclonedx-python-lib pull request #706
Opened 2024-10-13 13:13 UTC by saquibsaifee

2024-10-13 15:50 UTC, saquibsaifee commented
@madpah and @jkowalleck please advice if these changes are enough to add this validation.

2024-10-14 11:47 UTC, jkowalleck commented on cyclonedx/model/component.py
> +            raise ValueError(f'Invalid CPE format: {cpe}')
this behavioral change is a breaking change. 

this fact is not a blocker.

2024-10-14 12:02 UTC, jkowalleck requested changes
CPE is a complex, external spec - outside the domain of CycloneDX.
This fact leads me to the architectural decision: we do not want to maintain an implementation of this external spec in the domain of CycloneDX python library.

meaning: this PR will not be accepted in its current form.

we might consider a usage of an external library, like <https://pypi.org/project/cpe/>.

2024-10-14 14:08 UTC, jkowalleck commented
Thank you for the PR, @saquibsaifee .

I will close this PR for reasons detailed in https://github.com/CycloneDX/cyclonedx-python-lib/pull/706#pullrequestreview-2366402891

For a different approach, please open a new pullrequest.

2024-10-14 14:27 UTC, closed without merging