docs: reorganize responsibilities and capabilities sections in README.md
CycloneDX/cyclonedx-python-lib pull request #719
Opened 2024-10-22 17:19 UTC by HmbleCreator

Closes #485

This PR reorganizes the documentation in README.md to better structure the responsibilities and capabilities sections. The changes:

## Changes
- Restructured "Responsibilities" section to clearly outline the library's core functions
- Reorganized "Capabilities" section into logical subsections:
  - Enums
  - Data Models (Core and Vulnerability)
  - Utilities
  - CycloneDX Specification Support
- Improved readability with consistent formatting and hierarchical organization

## No Changes To
- Functionality
- API
- Dependencies
- Installation instructions
- Usage examples
- Other documentation sections

## Testing
- Verified all links remain functional
- Checked Markdown formatting
- Ensured all existing content is preserved

Similar to the organization in:
https://github.com/CycloneDX/cyclonedx-php-library#responsibilities

2024-10-24 12:02 UTC, jkowalleck requested changes
thank you for your effort,
please see my remarks below

2024-10-25 07:56 UTC, jkowalleck requested changes
these are great improvements.

lets discuss the reasoning behind the grouping of the models.

2024-10-25 07:56 UTC, jkowalleck commented on README.md
> +* 1.1
`1.0` is missing.
we do have support for it, dont we?

2024-10-25 07:56 UTC, jkowalleck commented on README.md
>  [license_file]: https://github.com/CycloneDX/cyclonedx-python-lib/blob/master/LICENSE
please _order_ the links back like they were. 
file-links were grouped, shield-links were grouped, external-links were grouped ...

2024-10-25 07:56 UTC, jkowalleck commented on README.md
> +#### Repository Models
the repositories are a mere collection of other tools.
please put them to their respective domain group

2024-10-25 07:56 UTC, jkowalleck commented on README.md
> +### Data Models
could you explain the idea behind this grouping? how is this organized, how came this together? 
I really love to understand your reasoning. You might have fresh ideas that are beneficial for the project :-) please share your thoughts.



I mean, all these models were based of [CycloneDX spec](https://cyclonedx.org/specification/overview/) -- they actually reflect it.
If a grouping was actually necessary, it should correlate with the CycloneDX spec groups somehow.

2024-10-25 07:56 UTC, jkowalleck commented on README.md
> +* Serial number generation for BOMs
i did not know we have this. could you point me to the code that does this?

2024-10-25 07:56 UTC, jkowalleck commented on README.md
> +* License expression parsing
i did not know we have this. could you point me to the code that does this?

2024-10-25 07:56 UTC, jkowalleck commented on README.md
> +* XML/JSON serialization helpers
we do have this, but we dont want to brag about it, thse are mere internal helpers for experts. we better not tell about them here. 
please remove,

2024-10-25 07:56 UTC, jkowalleck commented on README.md
> +* Hash calculation helpers
we do have this, but we dont want to brag about it, these are mere helpers for experts. we better not tell about them here.
please remove

2024-10-25 07:56 UTC, jkowalleck commented on README.md
> +### Specification Support
please make each version a code-block by surrounding it with `

2024-10-25 07:56 UTC, jkowalleck commented on README.md
> +### Enums
the description next to the enum types do not add much value, as they duplicate the enums name and add the word `type`. 
i'd rather remove the additional descriptions.

2024-10-26 15:02 UTC, jkowalleck commented
we just got a new set of models that needs to be added - see #701

2024-10-28 12:59 UTC, jkowalleck commented on README.md
> +> **Note**: This package is a software library not intended for standalone use. For generating Software Bill of Materials (SBOM), check out [CycloneDX Python][cyclonedx-python] or [Jake][jake].
use one of the falvors here:
<https://stackoverflow.com/questions/58737436/how-to-create-a-good-looking-notification-or-warning-box-in-github-flavoured-mar>

```md
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.
```

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

2024-11-04 14:26 UTC, HmbleCreator commented
> The efforts are appreciated very much. 💟 They just need an updated in accordance with the latest development. I am sorry for the inconvenience.
> 
> I've just put this very PR in "draft" mode. Feel free to change it to "ready for review" anytime it was updated, @HmbleCreator

Thankyou for your concern but I won't be able to work on it for a while, my end sem exams are ahead.

2025-01-15 12:12 UTC, jkowalleck commented
@HmbleCreator , I just wanted to ask how things are going? How were the exams?
Do you need any help with one of the open points/discussions in this ticket?

2025-01-28 08:01 UTC, jkowalleck commented
I needed these docs for a conference, so I will take this over.

2025-01-28 11:41 UTC, closed without merging